export const columnasCotizacion = [
  { id: 'id', label: 'ID' },
  { id: 'nombrecotizacion', label: 'Nombre de Cotización' },
  { id: 'nrocotizacion', label: 'Nro de Cotización' },
  { id: 'volumen', label: 'Volumen' },
  { id: 'area', label: 'Área' },
  { id: 'altura', label: 'Altura' },
  { id: 'cantidadventana', label: 'Cantidad de Ventanas' },
  { id: 'ciudadzona', label: 'Ciudad Zona' },
  { id: 'nivelpiso', label: 'Nivel de Piso' },
  { id: 'orientacion', label: 'Orientación' },
  { id: 'tipopared', label: 'Tipo de Pared' },
  { id: 'tiposuelo', label: 'Tipo de Suelo' },
  { id: 'tipotecho', label: 'Tipo de Techo' },
  { id: 'tipovidrio', label: 'Tipo de Vidrio' },
];
