export const columnasCotizacion = [
  { id: 'id', label: 'ID' },
  { id: 'ambientes', label: 'ambientes' },
  { id: 'descargarcotizacion', label: 'cotizacion' },
  { id: 'nombrecotizacion', label: 'Nombre de Cotización' },
  { id: 'nrocotizacion', label: 'Nro de Cotización' },
  { id: 'ciudadzona', label: 'Ciudad Zona' },
  { id: 'nivelpiso', label: 'Nivel de Piso' },
  { id: 'orientacion', label: 'Orientación' },
  { id: 'tipopared', label: 'Tipo de Pared' },
  { id: 'tiposuelo', label: 'Tipo de Suelo' },
  { id: 'tipotecho', label: 'Tipo de Techo' },
  { id: 'tipovidrio', label: 'Tipo de Vidrio' },
  { id: 'radiadoreje50cm', label: 'radiador' },
  { id: 'toalleroeje50cm', label: 'toallero' },
  { id: 'ducha', label: 'ducha' },
  { id: 'tipocaldero', label: 'tipocaldero' },
  // { id: '', label: '' },
];
